---
- :id: name
  :name: Name
  :placeholder: e.g. Insurance Company Inc.
  :type: name
- :id: address
  :name: Address
  :placeholder: e.g. 123 Main Street, Toronto ON A1B 3C4
  :type: text
- :id: website
  :name: Website
  :placeholder: e.g. www.insurancecompany.com
  :type: text
- :id: phone
  :name: Phone
  :placeholder: (Area Code) - Number (ext.)
  :type: phone
- :id: fax
  :name: Fax
  :placeholder: (Area Code) - Number
  :type: phone
- :id: users
  :name: Users
  :type: !ruby/class 'User'
