---
- :name: Name
  :id: name
  :placeholder: Firstname Lastname
  :type: text
  :required: true
  :primary: true
  :unique: true
- :name: Email
  :id: email
  :placeholder: Email (ex. john@consilium.ca)
  :type: email
  :required: true
  :primary: true
  :unique: true
- :name: Salutation
  :id: salutation
  :placeholder: Mr./Ms./Dr. (etc)
  :type: text
- :name: Position
  :id: position
  :type: dropdown
  :placeholder: ''
  :options:
  - Accountant
  - CEO
  - Insured
  - Manager
  - Owner
  - President
  - Principal
  - Admin. Assistant
  - Vice President
  - Other
  :intelligent: true
  :otherPlaceholder: Specify
- :name: Phone
  :id: phone
  :placeholder: 'Area code - phone #, ext #'
  :type: phone
- :name: Other
  :id: other
  :placeholder: Main, Direct, Toll, Fax, Pager, Cell, Home
  :type: text
- :name: User
  :id: user
  :type: !ruby/class 'User'
