---
- :id: name
  :name: Name
  :placeholder: Name
  :required: true
  :type: name
  :primary: true
  :unique: true
- :id: email
  :name: Email
  :placeholder: e.g. john@consilium.ca
  :required: true
  :type: email
  :unique: true
- :id: password
  :name: Password
  :type: password
  :if: $!readonly && users.$index == null
- :id: permissions
  :name: Permissions
  :type: dropdown
  :placeholder: Select a user level...
  :filter: permissions:true
  :options:
  - 1
  - 2
  - 3
  :required: true
  :primary: true
  :if: $!readonly && users.id != myUserId
