---
- :id: name
  :name: Name
  :placeholder: Name
  :required: true
  :type: name
  :primary: true
  :unique: true
- :id: email
  :name: Email
  :placeholder: e.g. john@consilium.ca
  :required: true
  :type: email
  :unique: true
- :id: password
  :name: Password
  :type: password
  :if: $!readonly && users.$index == null
- :id: permissions
  :name: Permissions
  :type: dropdown
  :placeholder: Select a user level...
  :filter: permissions:true
  :options:
  - 1
  - 2
  - 3
  :required: true
  :primary: true
  :if: $!readonly && users.id != myUserId
- :id: title
  :name: Title
  :type: text
  :placeholder: Position within company
- :id: phone
  :name: Phone
  :type: phone
  :placeholder: (Area code) - Number (ext.)
- :id: description
  :name: Description of role
  :type: textbox
- :type: separator
  :if: $users.permissions != 1
- :name: ''
  :id: appear_on_documents
  :type: checkbox
  :options:
    'yes': Appear on documents
  :if: $users.permissions != 1
