---
- :id: name
  :name: Name
  :placeholder: Name
  :required: true
  :type: name
  :primary: true
  :unique: true
- :id: email
  :name: Email
  :placeholder: e.g. john@consilium.ca
  :required: true
  :type: email
  :unique: true
- :id: password
  :name: Password
  :type: password
  :if: $!readonly
- :id: permissions
  :name: Permissions
  :type: text
  :filter: permissions:true
  :edit: false
  :primary: true
